version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer_app
    image: customer_predictor
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - TF_ENABLE_ONEDNN_OPTS=0
      - MONGODB_URI=mongodb://mongodb:27017/
    networks:
      - customer_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: customer_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - customer_network

  mongo-express:
    image: mongo-express:latest
    container_name: customer_mongo_express
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    networks:
      - customer_network
    depends_on:
      - mongodb

networks:
  customer_network:
    name: customer_network

volumes:
  mongo_data:
    name: customer_mongo_data